---

# NOTE:
# using the old linked data repo image just as an example

- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: linked-data-repository
    api_version: v1
    kind: Namespace
    state: present

- name: Ensure a deployment for linked-data-repository
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: linked-data-repository-deployment
        namespace: linked-data-repository
        labels:
          app: linked-data-repository
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: linked-data-repository
        template:
          metadata:
            labels: 
              app: linked-data-repository
              namepsace: linked-data-repository
          spec:
            containers:
              - name: linked-data-repository-api
                image: gsscogs/linked-data-repository:develop
                ports:
                  - containerPort: 3000

- name: Ensure service for exposing linked data repository api
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: linked-data-repository-service
        namespace: linked-data-repository
      spec:
        selector:
          app: linked-data-repository
        ports:
          - protocol: TCP
            port: 3000
            targetPort: 3200