---

# better dif engine to see if a change needs to be applied
- name: Ensure Helm Diff
  kubernetes.core.helm_plugin:
    state: present
    plugin_path: https://github.com/databus23/helm-diff

- name: Ensure the ingress namespace exists
  k8s:
    name: ingress
    api_version: v1
    kind: Namespace
    state: present

- name: Add bitnami repo as a source of charts
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami

- name: Deploy nginx ingress controller
  kubernetes.core.helm:
    name: nginx-ingress
    state: present
    force: true
    release_namespace: ingress
    chart_ref: bitnami/nginx-ingress-controller
    wait: true

- name: Set shared resource/definitions directory
  set_fact: resource_dir='{{ lookup('env', 'PWD') }}/resources'

- name: Ensure a kubernetes resource defining the behaviour of the ingress controller
  k8s:
    state: present
    force: true
    src: '{{ resource_dir }}//ingress.yml'